apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OTwdkh6hagu/8TGwOX1m/30dT/F2BdAQay6SZQ==,iv:dbMeuhkSWN3CHL3zGR9lINwVWNmmVeHsgNyDjWtSvU8=,tag:6DubNTzsJuP8SFttYbWOIQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:aWBJoz+cV/qtCjlA9TaR1LeJRDu277v6IQJI20SQNO2W3VIpKQ==,iv:A4l6/rwdt3G9+cVHUR5ESKHqobrohUvpuJfXL89eLpU=,tag:nBdlGEEbYcVp4X0MizC7AA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:6cJPTjmFx0psGK2r,iv:CAD7iKrdn1WTl/lKS1LUQnTE+Sc1r9QKXW2KUFzSaUM=,tag:dCjrLcUO7ROSPMlRJw385g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOVdUQTM0WXFQeFp0S2Uv
            S2FCYUdLNTdqcHkzZVpOUlFJa1NDNWFIaUFZCndOb2NPc2YzRzRCUjAvZGRrZzJP
            Zi9MQlN0c0lvMFY4NmFpU29PK0xwQWMKLS0tIFJOTnZnNEZXMnpqdC9CWUY2UnNO
            Vjg2bWhreTlnV3h2QlVxeE9QMW9kZkEKc7J8gpu7vTioqqTuzxOg66dWNfQYC+7D
            ZNaBRQrKYl+1cCWC0SZt5PxwGBLIfQbGaQmQeKvYwUU6rh5Yp9CvVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T13:00:00Z"
    mac: ENC[AES256_GCM,data:MG5OWiEbcZfar3y4QXBWort+UVjZ51M1XEg7P0O+cZ3oRfrzWwrlx7NBbjvOnjaSwokC5uwZ5eGpgfCHYf7Y4WTLyBWS6SzTVD54nhpa4JuUu33E1Kl1Ef33bFnZEXcCGfrCcqR+tkeHyN2zJaFojKq13aBLZJg/nEJhM6iWsmY=,iv:Uc4NbnnaSF7TWsGEC/DAEli8LcyNiIKm0MWr1Q8hGAE=,tag:L1OcSMMnjtHW0kSeBPObaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
