---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./csi-driver-nfs/ks.yaml
  - ./external-secrets/ks.yaml
  - ./kube-vip/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
