kind: ENC[AES256_GCM,data:Y5dSwe6C,iv:O41HQdP8nqolP6XyoDCFmsr3lmkAeZTS/atetVI7SZM=,tag:ZdCLK7IGKUHb65bYHV9QaQ==,type:str]
ansible_user: ENC[AES256_GCM,data:RjlmgL1HjA==,iv:iip6EJM/O/PaR+oNcMsk4HWO2Hn65DeNynMmiAnSEzM=,tag:aLwXpP5OEqiWoxy/52tFqw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ofBb4K0fTUrmdhmitHO2ww==,iv:dlM3TIgbJPRwu8im6Mo20GgLKw9SpR/Fth2uuixhuZo=,tag:wSek8sfZXWuVZn2xfxxDgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q0RJUWZjb2R3N2ZsT1hn
            aWo0b1JVUm5HNzFNQ2hYZ2dkeGIvWDR4cEdVCnNSSVhtbkw3cm1OakJST1gwcUcw
            bFBFMER0eUhJZ2J1R1cwQUlWYjBMcG8KLS0tIENkUnA0SDlOUUpLc2MzUU5QalRD
            R0pCZlhDaDdTRTgxMG04bjRkUHFqUVkK1Qnr/7Kv+GJNdYKu5CjK18YpliWFv1JY
            7jYzncMz7WIu6KosG0T+TgBDVYVEUbj4cnI2JVjwB5waw64AksCkRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T13:00:00Z"
    mac: ENC[AES256_GCM,data:d4KEApnkPntyr4JvBMzkPUEjAN5nYg/owLopTiR16Hdj6Cgx/qKUU0l4+7Z/98RlRK3pee2Q0YbtpOw/ZFwGN1ef/etzOJ9RDrglhRBlBvPASy0mDA+QMnlp1nFwbxC1jPuGkCLdQ+E5BNS+n3zU3rUZmN8qZd1ZQgRULnYNE9I=,iv:FvOOcAIK5sya0QsNblYSxWQCva5+Z7gTsDgKnx45bzk=,tag:jcuUIyf/esGHeOyTO7Mn1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
