kind: ENC[AES256_GCM,data:NW2j4tnY,iv:UZsPfrwvTx772I4iK49VTa6gQrjx9yryfxd+qlZxvNk=,tag:rZqpchFzHwZyRgZ5V93s2Q==,type:str]
ansible_user: ENC[AES256_GCM,data:PSEZ7DJgFA==,iv:b/EQk7W1SeTWPGOa+JLM+IQFqAVmM3FGewGwgpMrwYM=,tag:RNV+OOmN1rukG/iDbmZ0ow==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Qoy2FoJj4N6X20KB4MzWTQ==,iv:GM6fPhOuasN9IPqn9ZoRH6i3qKXXZEgVstRFzrxS0Ek=,tag:epCFNaWv1pdtz/BuvwQ1+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpY3grcFpZbGVMOEdwRXcy
            MmNDYU1aN2FxTFRnNkxCdHY2NDQ4ZSt5SWxBCmxvK0JTS3Y1Sk5rNVNBZHJKUlgy
            VjNwTVN2SHhtb3Zjcm9GSnhObXhBQjAKLS0tIE5XaXYzWUV0Q1QyeElsVWo3cW9w
            OUFqcDVMcE9rS2Y2NHdDVlBkcG9lOFEKGFwd2noF+TO+1jWeVOYsDiniSOYY12Pb
            fhHmPg4PQ6BaVraxMnPs1xkopP7s5s17EYEqTNReQmWBxNNA+WfLqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T13:08:50Z"
    mac: ENC[AES256_GCM,data:x7fBh0yg97iDWCw2sEh3VVp4++XvGHhjcrbJeZGVJM68Ez2J1JIRssbDb0SJHzBcOyyVTvVzIqGEFG7jGIUs5N9hQVchbBz8kWYWDEnpz1n0Zn28Pa/6jNMPfyiJfVlg4P+1XHWDgSOGmQBHaMxYl3n+2pLukQMxJ1nafa28Mi8=,iv:eGMLTXlWR9yM1UeGRuCJO+c+0u8D7XXCx8EfVQ6Ephc=,tag:ZSonGeOOG2eXU9uyBC5JiQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
