kind: ENC[AES256_GCM,data:l/x1zgd0,iv:q56DnZQBYQRCi5zAQW27K+2r6tjbvx2m0qT8dkGw/SY=,tag:sXjk6Kv42pA6CHZCX/xISQ==,type:str]
ansible_user: ENC[AES256_GCM,data:HXb364PL9g==,iv:OOmKa07HRLbXd4z2iYoGD09o2yu0avgHTUV+QkJE5p4=,tag:2mX9McaQI+XuyOK8GuurDg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PP77EdCxEAfy63qu2GdnoQ==,iv:PvOQOUHv+JheYSMzdsoyLS7Qca4OezZXjyNolMrLKck=,tag:qHbSTAMPZySFB5EsSj5FeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSFJFcGdwM2F2ZVhPeUFa
            V0NBQk5wS1ZKUXAyaUJpRHZYaG5EQTlIWkJRClRVVUphM1lqYVljL3BadFFUTDFH
            MHVVVUlpQ1NVTXo4bmgwVFQvcnYxOUkKLS0tIHgxY0FsZFR2NytFM3c1NUNoT3d1
            aVU2VDNPa01kNWlkK3lYMkdjY01JNDgK0eV68dZgZ3a4Wazc4zMqfz3A8CoZ/swj
            5BGBKvJDpFh6X5jKhSWEJXhKrRHytd6S8DGz62cU2RXmKo3jp7NqkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T13:00:00Z"
    mac: ENC[AES256_GCM,data:fyVWyN26+0b6RtJGLCuCYrfLoVHY496L0RICq1uwc6O/UJxwxNsW8iqefidPWAYI6Hs5F9DqD6srYHsZaTsxh+wU/yK0BW+5HtpdYHhea/uqYQBfIBV2a+LjPWw4qQnP7+qJ7Bd2e6ij0negFeXq3lLJQfeNdJwD7qLqkN5bbIY=,iv:MZM8AB82YkWwUkNskH24t2l5Yp5eJdUfYS+yTWsuQ3o=,tag:sVcGAuTkKfHfIkTUSPaU5A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
