kind: ENC[AES256_GCM,data:COr6aCiR,iv:9sjNglnsjU5eRcwSilOvdCFMjgsl0VYsVWhkbPiZh9g=,tag:8dVRLxlL0u/wrySahzzX6Q==,type:str]
ansible_user: ENC[AES256_GCM,data:hquBIpnfrQ==,iv:0NFL4TeqxszgimI2adTqsPFT16gzXFzJwD0jsTCmokc=,tag:Udbx5C6wfydbvPRB0FMMoA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:SGuBakAQmN98NzaX0oCnFg==,iv:Zhnm1bb7fFjBC603GQN49EOVYTpzQ6UI14KUl14cqA0=,tag:QAruf4XRd3GwPK7EotIp1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRldxZTE2UVF2TU1abGc1
            SjNGY2dTcEJpNFlPTTE0RjdYc2dSZWxOYjM4CjEwUDJ4OFNSeXhkQVN4K01rcEVj
            bjZneTA4MXVHWmxnUGY1NWIzWmhrTWsKLS0tIHdOMzRTVG1MTmtKaWNtaGMvSndu
            NzVRZzV6TzI3L3NrUU54eXRZWjZXVzgKRByWQvr8U6dxFhq/Qy65go3cDoTSvGzc
            Rh/n0eRmYrCVnLjgr+T33Q1usphTlTVYp3YOl3tO7SrFlG5NTY+jzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T13:08:50Z"
    mac: ENC[AES256_GCM,data:uXlz+jTlMoy0sAK4pZ76+MH+4/2ADEaF8j86tJTG2MlJjT2jwszS4xtDIxiXfpr7/OyYw0JzfLCYQMtoKnwMnw649Fd9szic7e+oZgnYS32aMCOX9drYeZw9boK6ZZHLgOJL/ukmRnpQFu/cdQ1/n/GGHnoyQbIcHWntPadyh7A=,iv:u7LN254kARVuuE1g5zKqhPGl1zJ76heW4QfOINUtmBM=,tag:uF4Si0tTu4cAefq+A5QJOw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
