apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ShoIw8N6iZD4Bbvjk5EPdnzSnj4KS7wagP1u4zjV1B0+Qg+Ktem/cg==,iv:MMB46itDrrRSTyc/+ZqzibzXsQR4MQnTo1DEbe882z8=,tag:CJKQlN8prVbzyy4FjHy1rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKclRUd0JZQ29LYkc1ekwy
            M3RuU0RMUXlPVHpRelVXdlR0T0JiWkFySUNNCnB4NHlFcmZBY3lxdVlGc1ZyNm5k
            MWpNSFJWVXlNdU9zUmtvUU5mQ25VRlUKLS0tIGM3TEY2R2g5bysraWtOUGRPakhL
            bUlRLzIybzZTSnRWdWRHdSs1UUZEcjgKUsC9HpmP2NEXlgB4N/njZHMwlrt7M2Eb
            NniAGnJFq63tNBwI+MvDNJboIFHWV155zscqD9rn9NRIX+GxYE2/TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T10:52:57Z"
    mac: ENC[AES256_GCM,data:r5yKWrL53uIhiFq+eOtTMmNsKCVeNJ1MEU1c9S0dCZmCSUoBP+DJEMCMjHZDP2/hEzZQWUKLddBl1WWtMEaKRPtQQGTnOFs44oFHIpPifLt4VEQQ+FJviJrbofjkz6QQqFXzVv6vHqPOBJXdZbsKQifWpmLIM82P5dDSHEjJ6SQ=,iv:6iOzG1ByZQ8F5EsW287QtkK1DUCS5En5o50tDryUfp8=,tag:piNrD6UYdCfsrJjgkyYOMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
