apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:zBUqCJ3j2NUNNrQcd2yINyBNHdTgJVOjn0cb8n99a4cuGc1LDwkc3w==,iv:5WWetBbSIXOjJxAHevrgAOzAh3vt/Dqc3UL0jcuDpvg=,tag:j/jy3b0d7QmK146SJzRTeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMFlOeXhzWm1WY3A0ZERO
            aTdkN2tXZC8wWjRsYklEYlEzQnVZTHZjR21vCjR1ZHQ5bUgreDFGMHkrTXVHWHN3
            dElJVTJnL0VaNTNsVDFQYzlRRi9tUVkKLS0tIGFLeTQySVdoQ1M2K3dPQWNBWXBx
            T3NjL3h4REVUVDF0aExYcDVjOUtXY2sKAL/Z9YdZnOxU0b0EtVQsC0T6RLWyN/48
            3OyOB5k4JFLAhuKHyEYUc2OSSRKhoL9g2uL44rHmJWK+asdHRAKCjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T13:02:32Z"
    mac: ENC[AES256_GCM,data:88XEj1xdZUlqzRIyM4NFLqysL/+Gwb415JVwN8J2uG95eIdM/WmpqfM0n4hWYH6SnlcdIJC0Rldii1zCwnPN1w9No90dL07RMEniYn14pk7FkAkxSfm/c/MdhljjU4FDqZz/fqC+C5JgjuSbNec+4QR/he9/3Mvzvec7jb3d6rg=,iv:HgS4refnpXc9Q9sBsSOSqhH9cR0pElcWS8zAdQg7ZVY=,tag:5hyZukaG6vhgqJpClT3D3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
