# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: kube-system
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:dtYJL/PUmXS3Pr1BrWtO3RFLzWj2JYNg69lCSQmGYCfZnhgrfIZRQEkkU8QHkjH+Z259bQKoDOJy05tc4XrePfNzXWHF40oYddUnyVUAz8cXQDHVn7AsLo0kdziDNK3mk6b15nMQncA0PdS/7QWa80KH4Bqs4qUNcF4jWK8flSa5bgf23ZUQnjbn2kQi5PJGfs9OOSVDM4DjrfUZaJebXH6bgKZoTJ8Nxy1cd9o5iKFfPfvFQHRPr+wC4bsKRlMnE2/71OXCiSjAMmkBFMkP+GtDeD3YxZ4WYZmli8ThR6OBKEFwnnSUZNHOMP6X2w1WaFD3nq/JkEoDzBR4RHksJ/08bLhB5tmWyrMoDX30KUPQSCy9+LGfzWf6tZAcjqdkdHffFufX8VPsQRfGe4daa1Q/WtmkiY6NoVLNnbmwzZts+ujOQDhsbPhyrDSxfWAnhWm1bWPPV1o5+6bEq+rsjmQtzOdSd/KMq2DrKPxxmruFybWmT54k7Q5c/nbJ25E5mN3u2YPoz3PtG7DWBRQXfHAlp9ZV7+xVU9Iy09hRozkMQnJZLKG3rI+IwstWYVKcmXsDayuRCjUwTjt4PHoUMJfDoLaWYxeCIk9f7PpgGrUrseN226GpgfYy2MYT1QKKPiAXhL0XA/b0VzhTPumZkZrGuZXxOp8grvT2rUQHtGEbnM+iyAGA6pMWEhIlZSGcnddm4uTq1GfQnh/T1yoNUnpMZjDPmfh8xrP/6vIbe8OsU9QLAgDj68Td6KclakxD9s5Z1gDOqPHcU9gDo4r8qH+3CZU4g9rCWe2LOqojIUBz793y4uy+lBp+91iYtNnB0BQYlBFJOCi/Uro5MaFk7pa8T+3KAKMeEm39LwdFEDb4atME0Arq37gTPlaTaGyLsFM5gCeEL68ncu08suD2T5BHxv7m/qfLCP2/doragTKSFWRcpArqMYOkWTQVokxTiL0ovws7a7b4T0Jt6z3BpcIKL9PpsO8K4k13QjYgZ8BVnKZjWDJFPB9a3bQrMVr+tMEyBcbzbsbdu6H2e/n9g6ZD83+yhR2lrvsIGidTCesVg4KEUrNsSRpJk08vqhEWnr8HLSJWyRKzZDTybJcR+IeEihU5VVeol8cpAiLEqbyTuyYbsb6VFmcT2hZJIbBwQwZdY5WAuv4P1XEp62WQRXdawjQkx6Iwa/lps8r3/79zi6EDyms3nnm84ages4NjDurlPBjGio9ecALtO9EhG9mLIawaNgHRdblSv72TDqb1jrSs43D2Mob6K5Ds2wchimTPyobZcowLWufFQGuuc36qW5OAH8gOHvyTkgYdxUrOY7w0Zg75swqooyiRc7SICVsYGyBmjOQgAaDEYToEMmwf6JELhFOGIsBXkEFQNzxr11/liglM8P13VSdX9xFJyyTHHCpVihZwB9R05i6gb3vDDsXPCoTteVYB6+5HkO8=,iv:YBopDE3+jF2FyuFKkWj1HXdcbtRxNCa2Ex3Pq5YUAH8=,tag:DSmmHihLhHl7qXVpK/amew==,type:str]
    token: ENC[AES256_GCM,data:quvrJ0HOe6fbaofseWnle5seR5SsKyF6JHZ0bsURNV0KcBhi+NCOsnjtMguuyCtwU7AOL7aTgzqlRmqvWqz/ZrkjhADamFZGMdzs0CWvmYfrV0oNwUYH47emtZx+ptOATAa5dXpoFFEZ4Den4u6AlePwG+BjU4PsYISxmyhobBiXGznfqaZR7bBFjYEYAjYzXtrl9zdMAQO9CSmQwaXWvdLwkqnM0qiaeZ4LRvJS1N7f0gkkRG3Bnz35t8Z7XCi3EJTFan5Oc3e5LOdgVrpZDAvBgNYy6JVLz5YeZNgY2kk=,iv:cIjTIxOfJFiXFFdsro4h2bpgYFP9Aj5ZfrkMb/Wub+g=,tag:ACuidGp2e0E1mcwYTGsa+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRDNTZnMwWTZ0disyK2dw
            QTFoZ3dKTXdFVmRPVFc3R3ErYjl4OEo4dEJzCng5SjFORUVUQndpWFNRTHdKYTNp
            NU51ejNJNW00eERZRkVkbkpGNkxlKzgKLS0tIHdmSXkrYjcxczI4M3luVXlYNEJY
            MEpRWURUZG42OWVpRksvT3FnSEdpOW8KlicwZRdqWKMTHcpXRd9j1ec8VWhiFx1l
            hH1GnGgBDN541kkqR/JDwIgFlIsZXWtdlre6o8li7e2IVma951pveg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-05T08:33:12Z"
    mac: ENC[AES256_GCM,data:92YEQ6BBg50AUnZtFAmhHfSFjQTI+6PFBp/OUAfAgqEcLdLLWopq52kwUaMFv0AMXSy+80ghP75abu0VEZbwle2Ek+Y634I2f5AOU44D5qcH/FfbiTvGPG33YyG4JiHngjjzu3pMo5UP/OUoTW4fJXkkCzBGbW20vgYU4CeKin0=,iv:+QpssoqgWwEHgAtEQHQKaDlG+SEL5TF/yHIX10sHBEk=,tag:3ACoDgLYUCZLT+/rhrjpTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
