# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: kube-system
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:k0H5ipbCSmXR/mOfAPrJ38iM+qjpZN5Im0D2Lg==,iv:IWFdnpleZmeGqZ4ssQSwJd9tAc+BhP2HTtCq57DIm9I=,tag:lmgICr+PPpFP1mfDTiqcCA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:ivKA3+TtVROVO5Iv+W0uuDgtIZDuYq5PFcQ9gI9JbIOtEZGlYg==,iv:ADniBnkzWMAWZbIEYSZKDGssQjsBlKzLo1cOQEzT/iY=,tag:KKVMOdXfdXwuJPgOACdWqg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:yJ4Qk26ko17CqDai,iv:22yl87VWmjuAABTAncWuBSUUbNfCyzrPkxBy6tYS3aI=,tag:B+jls8XkHItHabFVWdkICA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSR0h1UmlSNVYxTVpuNGxh
            UHZaSUJXYUVQMlhobXVUV1VQeExOMldkNml3Cm1hTmpFQWYxcjZnUmxDVG04d3Bx
            WExVWmJMbHBySDhkY2hjV1kwRDhTVVEKLS0tIFh2NDNZaUZRQTFZdVdUOXFOcUtm
            TEFOZlExUnkxUFpxWW1HZ0pLQXNHZzAKzBswiyOiE+Q2G4ag9Wi1pKkEpS1esoTv
            BHxAxXrKTstDdObmfFm96hfjQtMVt/pJskJfYZToSg/gN9zoHhdCDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-21T15:50:15Z"
    mac: ENC[AES256_GCM,data:k971R5pbydZai/758z66laJWph0d5+tvLJ831SgE1JTSdX3JVQCVyURftw4OwUmR+d7DS2vBnAseZBJjrr3grI88KJNRE3znU6dQ5MnR3DPLXrUQzPwDxwh3kcoM7u690QtaF1i4Fm70YP6ITZTnSDggdLvnRK06YGIqSHTi85k=,iv:pwnIrDJuyM6ce0q9JCmJvuwF/0Y0m4ETVSlWhk4OYOM=,tag:9narx+JAgjxtFRZ12tTngQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
