apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Rm4knOxEYJWPK+Ban9C2vRa9AhSOZvDlRNyw6SDs4ohyH42WMg==,iv:8G4hBHEqcOdo74ssQ4+2rci5vZyFJuyhv/hbbrC7tIw=,tag:lFSUIk101sle0zHR5Lw8/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOWUrQ1dXMk9NYlU5cUtq
            R0RjV1Nvem90bUFTZFB3Q3lmUitRZVBuNkhVCk9uZ0pIOVZqNFdtVUxjWUhKamZX
            Wm5WcTVteGUzMHJzTElXVEkwQzBGajQKLS0tIGozNkkyQ0FLNjVkVVd4czJmL3h2
            WUdJK0t1V3FVR0E3SWhjYU5hL0llN2MKmxziT2+Ur6HppDPX9Lez2VkAFj09zEMY
            He5pzaWWXJEWWjA22zxnhvSZnGNx1PWeqQTLycXgfTPPYpJBVPaaGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-02T10:04:26Z"
    mac: ENC[AES256_GCM,data:nunnpmBCnMxLfOl6ImERcs3HhuHgHHuNcAIFXkIIevyYIqygRcbMSnRKwisa45R4uKnHIrsgJ65gmdyasPjaqEIWll1s0sehYL4L1gDLk+CvJxmsIdG6qwB6YNpsCyPVc01EdnsvdSK1w/q/QyBeiFEj+WJ1wPzxAILI6AZkMXg=,iv:1drfUNOV70chmRWA1MH4W3Hheg2PttCf0nE0rVFo5Bw=,tag:jNpuO+BsoSPYIkvkwikijw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
