apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:MVxmgzeZfn1KzGGH3J/XKK4U2O8GfEm7NlghLA==,iv:Aa+FGKywE8JCDikWvAGi7C4wXsWCaPUfWEsKVexfN2s=,tag:UhtC4ApmHbtUfb0tpbp9bg==,type:str]
    api-key: ENC[AES256_GCM,data:+XRC7BUCFG8hZEVAJSaqMPpwVzbsph7gyJsnZ9IPPQlq9B/vPg==,iv:1BhX65GCSxN7BBX8NApCUbHGNmAUgkAxaxmLbt4KAno=,tag:FmkUBN8/8nX+GYeHaHy11Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4clhYTGJ6TGhzNG5TT2E1
            QlEyRlFpYnQ5UGI5aU9uenllL1pnVGk0UWs4CklVZXdvaVJpVWRGSUxLSUlscUlQ
            cDVwMXFyZzNCUS8wVXAyaVZ4N2FleHMKLS0tIEtwNHR3NVk2cVVHNloxbzFZOE1z
            V2pHeVYyRm43T2hxV1FONlRDVVdPcFUK3yMHaFs1hF5UYlqKW/Vl33zEVm5UIfaC
            vV2nxQ+apffJ8eiPWdkMSjfhFVhuD5GkFCxBS2N3jpPHgRO7Uy2QqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T10:52:57Z"
    mac: ENC[AES256_GCM,data:6vphH6+VqVc/NzBBJv2449UUKGFNcATZqCqBRmKQ5GJbEHsBy6f7TtDPFShlyo2yqYEOqEXT8iTEog9kJF765miDDqBy3GRTwrBBGY0mBhIxQNuRnoE2v72coPUFdzv+tcUkiS+QHErwe9wCOg0jjg93vdrL8O5AJnw16QGcWjA=,iv:kBM10fLP84WBucn4qWCbBGIO6wZk+N3AkwHfMnRbDlk=,tag:AWu+djB9nbFgu874XcaMCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
