apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:ZyHQE7fe1P1+jz4Iv1leVUHaEHViU0IeJbi1wgKDEn0QvjulGB0e5z/ySIjK9LfqNgPBijW6F6ckWstn,iv:s84ABihbqdsXYtHgZvT+Co6cAwPD9aNKELX4YetQOSQ=,tag:k9w+tmIk/q4UgRgD2iwp2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZFV5eC84Y1BaQzM3aTk3
            bVlkSTEvaHZOeHBERzU5M0dnNGVPcnVyMVZNCllpMEswTTlHT3dNL1lVeXJ6T2ZJ
            cS9hbkhiVWloUWsvaHZmUkRNc1BhWncKLS0tIDdpQzNQazdKNGh0aXgwRHNWc2pO
            WEY5TWprWGdQWEpkNVlmRXlHVmV4Z3cK7SFJi3FS2YSXBK36hRFM1T3GMRC4MgHQ
            1OdKALgwWztkYuWq19A8wT7iEyDmh/U8lQYxFqIFay8py4ZzHeRM3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-02T10:04:26Z"
    mac: ENC[AES256_GCM,data:bUhOPcSDDNWh8CRqnzUPaH0eTJND038rjFXPvq/YbxC8GBlVPJmRB8efR7ZVBpzTsH8twDPv5pEdf1h0laULVZAwIz+hAOZMnw6yG1im+jpHtYStzHQm+hd0tVnv4lnuZxrQAUAp5dZtOwJTf2/vixcKMeYtVA+kQJ/VLpz8mXE=,iv:XzO6sp5e8jIGYpUlwcbg6z7ZBReiJaoD9DqMgSm9PDU=,tag:lo+UkIq1VLPWUmVt1guAgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
