apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:CP9BqABkVVHR0YSgMg2g3v76geWa8RekiOmXBv2Yb10SuQL6vdW7JYchxqoRpjnkdnSShjS8V6dajPuN,iv:RJr9RXmPM+LJhCCGEHyE3Y0vnDuB9YB0koMnD0+pL30=,tag:eLgPN/FoX09McgvVOqfnoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eWpZNkRlQmpwcGx3bjh5
            VEx2YklEdElBa2dLdXJ1SXVjWEFkam9CR0ZRCm4xZlJLaWpLckxzOHkwVkpkKzY1
            WHd0Rm5TTm9INUtUZ0tHTDFZRDl1ak0KLS0tIHhoZnhYd2crcTNQZGZaN09BemIr
            T3Z1ckFGQjdyUzJDdDJMN0VYM3AremsK0Xwwm70BCuYVbBo1DcdWJHe37eQRBcHW
            A2JY4GEjyZAhJ313LlGHIUexntC05gh35j/1CHBjDQ+qzibUjwgDdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T11:36:54Z"
    mac: ENC[AES256_GCM,data:gJm6FqLeCPDKxvtOWKYKbVJEK/01nlm+HJdhCexSzLVDgQuPnTswtpUaBrK9Qlv2uSoa8Zj5d7N9BlVJOmZxBh6j+ss56BYGu1PkLJN3GduUP3pQFoXtIhzkyhmwVosW1L7Nu8yd2WHVzRbSajCcMpzuhPI9vTMLw7AevpXJPUw=,iv:pdk6HfosSNgdhoQuOCxDAoo0MEE7iVNZJ6b4uzDSTaA=,tag:ctx8eFkV1Ko5ztRGAlyPzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
