apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:xoXt5Th1rw==,iv:AC63Fu96UfIzjUc+gh82vwRZ5lB6vCKH34lbhltXGkI=,tag:sQNFgjW7sOE4UNybugvZxw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:d8xuOhztkUWwVFthQzVoolW5TFakfMcMcTd3nQ==,iv:6Oz7KuBLRNL0quygpJom3NS6KMBM40tEMjPoRDeF5Kw=,tag:SAR27EcnXSznzqFFpKCpRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUEVtczFGWWVGUU8xR0dM
            bm0wSERtRTZ5Y1NtT2xLQmsrUE1UQ2tobFJBClBtcVN3Y1RvMi9tZTRyNHZwdFhn
            SStaSDk0dkZTL2hYODFIUG5ER1Y2NkkKLS0tIC95WGJBVDVTOTNwa3FvTitrRmh4
            djJuSTB4K0c0eWJYZUdnN1FKUUNUODQKDMFpGR3FTP0OI/ziTf0PmAjFSrmsgrH6
            1TEo5hMbjfLLeUOC/6TL4WpcII9m7keGEdcx/icnw9WvK2Gy02i0gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T13:02:32Z"
    mac: ENC[AES256_GCM,data:1B8I0Py4SCj68/bfi3+6hnox+rYeuvyQEVZ30Pz9rqijiOuhn2/np5ga/9O4IaSGcSefgP03qlaE94C0boYDcmM8Bt3PjqBNufBBG2AlxZQhleYQMObTIo/r23WE9fM2yADmSYCEpLAqv5gkT327wQj+nbUrUvmXgrC4ampyncQ=,iv:7DvdbIk0GkGqQmUgWhsb2rXUVJD4xgnVIrrpnhOKMm8=,tag:byVgOSCkexTqYL5mM3D8Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
