apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kPjmtrYIew==,iv:/CLeg1Dep0zWcKVL7ol7nj6fcarVOYknFn5EL80EpXo=,tag:zXkvCOekNtH4+JOt03e/Dg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uQFqBm4fSiZAo6LwAJOKg2+GhWpR8BrtA+m3+A==,iv:9ao8j8OsPylq47xEHiD6+k5PNcGKXueUsxYgQnxHETg=,tag:nDDvQ0FMWDIzazOVpsylUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvejUxdWJNdUd5ZlZRR29s
            ZXptSTFYYnRmM2N4T1Y3N1Z2R0U2K1Rzc25JCjFXK3RhQ25LNzlQRXhLVExJUFI0
            cTEreU51b0pKMzZtWGZkbUxMeGQwOTgKLS0tIHBKNHBTWmI0NTdOSVBaNkVoN3Bh
            SkZNT1NMaU03RGFaQklyRTdFQjZ3S00KnD466HzbLdNl0BvzqhlwsiJpYvQ/oqLV
            gYXxLL/hlbcw2/1PMfMM1XWNKJTd+zsBcIPw5pTSXFqQ6NFpSPN9BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T11:36:54Z"
    mac: ENC[AES256_GCM,data:VKhOPEhn+QPB6evDA8rTMl1Yz8PJpsfWoGka7frqAlqFKB14TZ92Jbcj3x7XvCmDQ/oXrqIuIjazvWEe6XhBRu9jZ1agIBiSjFF0lGbnWpKzleymWUKE2x88XQHzVaAAA+HnHa97pO86opijV5n2a73w3V06aVV+jqJCKw5hCnI=,iv:utU++OAjg8/GcVy69MBfTMGjL+0PCzt1YsnYSbVppD4=,tag:VRmRT6C6i3OGrjVF0YXlwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
