---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-ip
  namespace: networking
spec:
  ipAddressPools:
    - default-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: networking
spec:
  addresses:
    - "${METALLB_LB_RANGE}"
---
apiVersion: metallb.io/v1beta1
kind: BGPPeer
metadata:
  name: default-pool-peers
  namespace: networking
spec:
  myASN: 64512
  peerASN: 64513
  peerAddress: 10.10.10.1
