# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:B04PTa35jAzZ2kj6GFznW+Zzo2gsrEMEVbmM2/5WWUxacuPpeA==,iv:PlkSMPagGEAXhPhNAHrWJxXetPvHECpBOzMyLpH6Eoc=,tag:mtBKlbH0Jorpd8ds2M/nCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdFZvSXl4ZlRrWGk1MnBl
            WEZnc1UzclV0SnJ3T2VFaVRmV1VreHluRGtnCmZ0NGlQR3VZeEMzdmZNS1c1b3E0
            SENVTFRJUUdzOEdBeitXL2o2blNyK1kKLS0tIHRUa2NxaW9sNk8rUnJQaEVKRTFX
            a1NIM3MzYjlWL2ZQTFliZGxzcGo0WGMKjoiuNxQ6mLEmWFcjnTmDGBH+J+FStRjL
            8Y0giP60hsee+a413oVR6ErAfLi6s9V2WPoWE0vbA1uQumkAcfO3QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-21T15:50:15Z"
    mac: ENC[AES256_GCM,data:JMsZVX8HxCg8SGYTrpz5MYZoBN49kXnvwAOPzglMwzizS5sZ7uoJD6a34NrW2ngLEcGp9MskYLB+ppiGQ14DZPrsSCa8BhQh8uqZv3BPwE7jAfGKwpWob5WvAGJSa9KyHMSvcmj0kTP1RenmwsvZpttp1A5E7ApWg0n4wrtMrpY=,iv:Y27VkOlylZaB/5yW9/hOrOcI2R7QZNeNDYxtGryjJZg=,tag:XHLS5VYqDgK8NDhtT/YDvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
